# Generated by Django 3.1.3 on 2021-04-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationAndVerification', '0002_auto_20210403_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationAndVerification.about'),
        ),
    ]
