# Generated by Django 3.1.3 on 2021-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationAndVerification', '0003_auto_20210403_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
