# Generated by Django 3.1.3 on 2021-04-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationAndVerification', '0004_user_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
