# Generated by Django 3.1.3 on 2021-04-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationAndVerification', '0005_auto_20210409_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
