# Generated by Django 3.1.3 on 2021-04-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationAndVerification', '0006_auto_20210410_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='twitter_profile',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='website_link',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='contact_email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='facebook_profile',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram_profile',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='paragraph',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
