# Generated by Django 3.1.3 on 2021-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotStation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempusermessage',
            name='last_incoming',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='tempusermessage',
            name='last_outgoing',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tempusermessage',
            name='number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userclone',
            name='contact_no',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userclone',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userclone',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userclone',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userclone',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userclone',
            name='username',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
