# Generated by Django 3.1.3 on 2021-04-09 16:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotStation', '0002_auto_20210408_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModelClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('draft', models.BooleanField(blank=True, default=True, null=True)),
                ('tags', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='userclone',
            name='profile_image_path',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
