# Generated by Django 3.1.3 on 2021-04-03 04:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=80)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('written_by', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('liked_by', models.TextField(blank=True)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('comments', models.IntegerField(blank=True, default=0)),
                ('draft', models.BooleanField(blank=True, default=True, null=True)),
                ('banner_image_url', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('by', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('blog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogStation.blogmodel')),
            ],
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tag_model',
            field=models.ManyToManyField(to='BlogStation.TagModel'),
        ),
    ]
