# Generated by Django 3.1.3 on 2021-04-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
